# Generated by Django 2.2.11 on 2020-04-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('sha', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('full_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
