# Generated by Django 2.2.11 on 2020-04-09 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watcher',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.GithubOauthUser'),
        ),
        migrations.AddField(
            model_name='watcher',
            name='repositories',
            field=models.ManyToManyField(to='api.Repository'),
        ),
        migrations.AddField(
            model_name='commit',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='api.Repository'),
        ),
    ]
