# Generated by Django 2.2.11 on 2020-04-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200409_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='message',
            field=models.TextField(),
        ),
    ]
