// Constants

export const GET_ALL_COMMITS = 'GET_ALL_COMMITS';
export const GET_ALL_COMMITS_SUCCESS = 'GET_ALL_COMMITS_SUCCESS';
export const GET_ALL_COMMITS_ERROR = 'GET_ALL_COMMITS_ERROR';

export const ADD_COMMITS_FROM_REPO = 'ADD_COMMIT_FROM_REPO';
export const ADD_COMMITS_FROM_REPO_SUCCESS = 'ADD_COMMIT_FROM_REPO_SUCCESS';
export const ADD_COMMITS_FROM_REPO_ERROR = 'ADD_COMMIT_FROM_REPO_ERROR';

export const GET_COMMITS_FROM_REPO = 'GET_COMMITS_FROM_REPO';
export const GET_COMMITS_FROM_REPO_SUCCESS = 'GET_COMMITS_FROM_REPO_SUCCESS';
export const GET_COMMITS_FROM_REPO_ERROR = 'GET_COMMITS_FROM_REPO_ERROR';

export const SET_PAGE_NUMBER = 'SET_PAGE_NUMBER';
export const SET_PAGE_LIMIT = 'SET_PAGE_LIMIT';
export const REMOVE_ERROR_MESSAGE = 'REMOVE_ERROR_MESSAGE';
export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
export const SHOW_SUCESSFUL_MESSAGE = 'SHOW_SUCESSFUL_MESSAGE';
export const REMOVE_SUCCESSFUL_MESSAGE = 'REMOVE_SUCCESSFUL_MESSAGE';
